config/routes.rb
Rails.application.routes.draw do
  get 'balances/index'
  get 'balances/new'
  get 'balances/create'
  get 'balances/edit'
  get 'balances/update'
  get 'balances/delete'
  get 'balances/show'
  get 'use_points/index'
  get 'use_points/new'
  get 'use_points/create'
  get 'use_points/edit'
  get 'use_points/update'
  get 'use_points/delete'
  get 'use_points/show'
  # get 'transactions/index'
  # get 'transactions/new'
  # get 'transactions/create'
  # get 'transactions/edit'
  # get 'transactions/update'
  # get 'transactions/delete'
  # get 'transactions/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :transactions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/balance.rb
class Balance < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord
has_many :use_point
end

app/models/use_point.rb
class UsePoint < ApplicationRecord
    belongs_to :transaction
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/balances_controller.rb
class BalancesController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

  def show
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions = Transaction.all
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

  def show
  end
end

app/controllers/use_points_controller.rb
class UsePointsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balances_helper.rb
module BalancesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/use_points_helper.rb
module UsePointsHelper
end

app/views/balances/create.html.erb
<h1>Balances#create</h1>
<p>Find me in app/views/balances/create.html.erb</p>

app/views/balances/delete.html.erb
<h1>Balances#delete</h1>
<p>Find me in app/views/balances/delete.html.erb</p>

app/views/balances/edit.html.erb
<h1>Balances#edit</h1>
<p>Find me in app/views/balances/edit.html.erb</p>

app/views/balances/index.html.erb
<h1>Balances#index</h1>
<p>Find me in app/views/balances/index.html.erb</p>

app/views/balances/new.html.erb
<h1>Balances#new</h1>
<p>Find me in app/views/balances/new.html.erb</p>

app/views/balances/show.html.erb
<h1>Balances#show</h1>
<p>Find me in app/views/balances/show.html.erb</p>

app/views/balances/update.html.erb
<h1>Balances#update</h1>
<p>Find me in app/views/balances/update.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    @FetchRewardsExercise
    by Erica
  </small>
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<h2>
<%= link_to 'Transactions', transactions_path %>
</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FetchRewards</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <br>
  <%= render 'layouts/header' %>
  <br>
    <%= yield %>
  </body>
</html>
<center><%= render 'layouts/footer' %>

app/views/transactions/create.html.erb
<h1>Transactions#create</h1>
<p>Find me in app/views/transactions/create.html.erb</p>

app/views/transactions/delete.html.erb
<h1>Transactions#delete</h1>
<p>Find me in app/views/transactions/delete.html.erb</p>

app/views/transactions/edit.html.erb
<h1>Transactions#edit</h1>
<p>Find me in app/views/transactions/edit.html.erb</p>

app/views/transactions/index.html.erb
<h1>Transactions</h1>

<table>
  <thead>
    <tr>
      <th><u>Payer</u></th>
      <th><u>Points</u></th>
      <th><u>Time</u></th>
      <th colspan="3"></th>
      <th rowspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.order('updated_at DESC').each do |t| %>
        <tr>
        <td><%= t.payer %></td>
        <td><%= t.points %></td>
        <td><%= t.created_at %></td>
   
        </tr>
        <% end %>       
    </tbody>
</table>

app/views/transactions/new.html.erb
<h1>Transactions#new</h1>
<p>Find me in app/views/transactions/new.html.erb</p>

app/views/transactions/show.html.erb
<h1>Transactions#show</h1>
<p>Find me in app/views/transactions/show.html.erb</p>

app/views/transactions/update.html.erb
<h1>Transactions#update</h1>
<p>Find me in app/views/transactions/update.html.erb</p>

app/views/use_points/create.html.erb
<h1>UsePoints#create</h1>
<p>Find me in app/views/use_points/create.html.erb</p>

app/views/use_points/delete.html.erb
<h1>UsePoints#delete</h1>
<p>Find me in app/views/use_points/delete.html.erb</p>

app/views/use_points/edit.html.erb
<h1>UsePoints#edit</h1>
<p>Find me in app/views/use_points/edit.html.erb</p>

app/views/use_points/index.html.erb
<h1>UsePoints#index</h1>
<p>Find me in app/views/use_points/index.html.erb</p>

app/views/use_points/new.html.erb
<h1>UsePoints#new</h1>
<p>Find me in app/views/use_points/new.html.erb</p>

app/views/use_points/show.html.erb
<h1>UsePoints#show</h1>
<p>Find me in app/views/use_points/show.html.erb</p>

app/views/use_points/update.html.erb
<h1>UsePoints#update</h1>
<p>Find me in app/views/use_points/update.html.erb</p>